// Generated by https://quicktype.io

export interface ILoginResponse {
  accessToken: string;
  id: string;
  username: string;
  refreshToken: string;
  role: Role;
}

export interface Role {
  id: number;
}
