// Generated by https://quicktype.io

import { ITagRead } from "../../tag/services/interface";
import { ITechnologyRead } from "../../technology/interface";

export interface IProjectRead {
  id:  string;
  name: string;
  description?: string;
  thumbnail: string;
  videoUrl: string;
  status: number;
  year?: number;
  clientName?: string;
  tags: ITagRead[];
  technologies: ITechnologyRead[];
  repos: IProjectRpoRead[];
}

export interface IProjectRpoRead {
  id: number;
  name: string;
  description: string;
  platform: string;
  url: string;
  public: boolean;
}
