// Generated by https://quicktype.io

import { SourceControlPlatformEnum, StatusEnum } from 'src/app/common/enum';

export interface IProjectCreate {
  name: string;
  description?: string;
  thumbnail: string;
  videoUrl: string;
  status: number;
  year?: number;
  clientName?: string;
  tags: IProjectTagTechCreate[];
  technologies: IProjectTagTechCreate[];
  repos: IProjectRepoCreate[];
}

export interface IProjectRepoCreate {
  name: string;
  description: string;
  platform: string;
  url: string;
  public: boolean;
}

export interface IProjectTagTechCreate {
  id: number;
}
